### ISSUE TITLE
Removal of local injection from scripts

### ISSUE THREAD

**Issue by Eutherin** [Adriftus-Studios/network-script-data#339]
things like `inject locally` need to have a `path:` attribute in the future, we should go through and update scripts as we have time

![image](https://user-images.githubusercontent.com/25861695/119549768-6c798700-bd4c-11eb-9165-69aa68d5566d.png)

Old style:
```yml
graves_data:
  type: world
  debug: false
  load:
    - if <server.has_file[data/graves.yml]>:
      - yaml id:graves load:data/graves.yml
    - else:
      - yaml id:graves create
      - yaml id:graves savefile:data/graves.yml
  save:
    - ~yaml id:graves savefile:data/graves.yml
  events:
    on server start:
      - inject locally load
    on delta time minutely:
      - inject locally save
```
      
 future warning safe style:
 
 ```yml
 graves_data:
  type: world
  debug: false
  load:
    - if <server.has_file[data/graves.yml]>:
      - yaml id:graves load:data/graves.yml
    - else:
      - yaml id:graves create
      - yaml id:graves savefile:data/graves.yml
  save:
    - ~yaml id:graves savefile:data/graves.yml
  events:
    on server start:
      - inject graves_data path:load
    on delta time minutely:
      - inject graves_data path:save
   ```
